# Generated by Django 4.2.8 on 2023-12-07 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_recommendation_result_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='categories',
            field=models.ManyToManyField(related_name='problems', to='training.category'),
        ),
        migrations.DeleteModel(
            name='ProblemCategory',
        ),
    ]
