# Generated by Django 4.2.8 on 2023-12-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_alter_problem_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='verdict',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
