# Generated by Django 4.2.8 on 2023-12-07 08:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0011_alter_recommendation_verdict'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
