# Generated by Django 4.2.8 on 2023-12-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0012_level_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='level',
            new_name='mu',
        ),
        migrations.AddField(
            model_name='level',
            name='sigma',
            field=models.FloatField(default=8.333333333333334),
            preserve_default=False,
        ),
    ]
