# Generated by Django 4.2.8 on 2023-12-07 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0013_rename_level_level_mu_level_sigma'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ('-created_at',)},
        ),
    ]
