# Generated by Django 4.2.8 on 2023-12-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0014_alter_recommendation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='is_for_diagnosis',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
