# Generated by Django 4.2.8 on 2023-12-19 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0015_recommendation_is_for_diagnosis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ('-result_date',)},
        ),
    ]
