# Generated by Django 4.2.8 on 2023-12-19 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0016_alter_recommendation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ('result_date',)},
        ),
    ]
