# Generated by Django 4.2.8 on 2023-12-22 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0017_alter_recommendation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ('-result_date',)},
        ),
    ]
