# Generated by Django 4.2.8 on 2023-12-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0018_alter_recommendation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ('result_date',)},
        ),
        migrations.AddField(
            model_name='recommendation',
            name='source',
            field=models.CharField(choices=[('codeforces', 'Codeforces'), ('system', 'System')], default='system', max_length=10),
        ),
    ]
