# Generated by Django 4.2.8 on 2023-12-22 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0019_alter_recommendation_options_recommendation_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='source',
        ),
    ]
